### ISSUE TITLE
Create database does not use utf8mb4

### ISSUE THREAD

**Issue by robertlemke** [flownative/localbeach-phar#10]
In GitLab by @markusguenther on Jul 10, 2019, 14:19

When initializing a new project with datebase, the created database has utf8 instead of utf8mb4.
Would be nice to have utf8mb4 as default, as neos uses this now as default :)

```The selected database's character set is "utf8", however changing it to "utf8mb4" is urgently recommended. This setup tool won't do this for you.```

**Comment by robertlemke** [comment]
In GitLab by @markusguenther on Jul 10, 2019, 14:21

changed the description

**Comment by kdambekalns** [comment]
The server variables are set to this right now:
```
character_set_client = utf8
character_set_connection = utf8
character_set_database = utf8
character_set_filesystem = binary
character_set_results = utf8
character_set_server = utf8
character_set_system = utf8
```

```
collation_connection = utf8_general_ci
collation_database = utf8_unicode_ci
collation_server = utf8_unicode_ci
```

**Comment by kdambekalns** [comment]
Not yet tagged…

**Comment by kdambekalns** [comment]
@markusguenther assuming you have the latest `beach` release, you can edit `/usr/local/Cellar/beach-cli/0.11.3/lib/beach-cli/localbeach/docker-compose.yml` as per c332c96 and the do `beach localbeach:stop && beach localbeach:start` to test this. Feel free to include eea7bc2  as well. :)

**Comment by kdambekalns** [comment]
After some more testing I concluded 0.12.0 works and released it, so `brew update && brew upgrade` should make it work.
