### ISSUE TITLE
On local:down the database didn't get removed

### ISSUE THREAD

**Issue by robertlemke** [flownative/localbeach-phar#15]
In GitLab by @jonnitto on Jul 23, 2019, 09:21

If I enter `beach local:down` the database didn't get removed

**Comment by kdambekalns** [comment]
For me that would be entirely unexpected, the database is supposed to survive.

What you seem to want is a defined way to completely "remove" a project from Local Beach. Maybe a flag like `beach local:down --drop-database`, which in turn would need support for creating a database with `local:start` (or auto-creation of the db if it's missing.)
